development:
  adapter: mysql2
  host: localhost
  database: facture_development
  username: facture
  password: blackjack
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: localhost
  database: facture_test
  username: facture
  password: blackjack
  pool: 5
  timeout: 5000
